language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t mateusz/docker-workflow -f Dockerfile.dev . 

script:
  - docker run -e CI=true mateusz/docker-workflow npm run test
