language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -f Dockerfile.dev . -t mateusz/docker-workflow

script:
  - docker run -e CI=true mateusz/docker-workflow npm run test
